# Generated by Django 3.2.25 on 2024-11-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('wip', 'In Progress'), ('done', 'Done')], default='todo', max_length=10),
        ),
    ]
